set(SDL2_INCLUDE_DIR "${SDL2_PATH}/include")
set(SDL2_LIBRARY "${SDL2_PATH}/lib/libSDL2.dll.a")
set(SDL2_IMAGE_LIBRARY "${SDL2_PATH}/lib/libSDL2_image.dll.a")
set(SDL2_MIXER_LIBRARY "${SDL2_PATH}/lib/libSDL2_mixer.dll.a")
set(SDL2_TTF_LIBRARY "${SDL2_PATH}/lib/libSDL2_ttf.dll.a")

find_path(SDL2_INCLUDE_DIRS NAMES SDL.h PATHS ${SDL2_INCLUDE_DIR})
find_library(SDL2_LIBRARIES NAMES SDL2 PATHS ${SDL2_LIBRARY})
find_library(SDL2_IMAGE_LIBRARIES NAMES SDL2_image PATHS ${SDL2_IMAGE_LIBRARY})
find_library(SDL2_MIXER_LIBRARIES NAMES SDL2_mixer PATHS ${SDL2_MIXER_LIBRARY})
find_library(SDL2_TTF_LIBRARIES NAMES SDL2_ttf PATHS ${SDL2_TTF_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2 REQUIRED_VARS SDL2_INCLUDE_DIRS SDL2_LIBRARIES SDL2_IMAGE_LIBRARIES SDL2_MIXER_LIBRARIES SDL2_TTF_LIBRARIES)

mark_as_advanced(SDL2_INCLUDE_DIRS SDL2_LIBRARIES SDL2_IMAGE_LIBRARIES SDL2_MIXER_LIBRARIES SDL2_TTF_LIBRARIES)
